### ISSUE TITLE
Maximum recursion depth exeption

### ISSUE THREAD

**Issue by linusg** [furmada/PythonOS#20]
**First of all: great job. I've not seen such an awesome project. I did not walked trough the full sources, but this has been a lot of work I think.**

While looking over the apps and all the functionality, I got the following traceback. Sorry, don't know which app I had open :(

Some infinite recursion which is stopped when the default recursion depth is reached... Hopefully I can contribute something to resolve this issue.

**EDIT:** I ran the code under **Ubuntu 16.04 LTS** with **Python 2.7.12** and **Pygame 1.9.1release**.

```
Python OS 6 Error Report
TIME: 2016-09-25 14:58:55.693280

Open Applications: ['image-viewer', 'task-manager', 'about', 'home']
Message: Event execution error
Additional Data:
Click event: <__main__.IntermediateUpdateEvent object at 0x7f132a8816d0>

Traceback:
Traceback (most recent call last):
  File "pyos.py", line 2648, in main
    clickedChild.onIntermediateUpdate()
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 553, in onIntermediateUpdate
    self.internalClickOverrides["onIntermediateUpdate"][0](*self.internalClickOverrides["onIntermediateUpdate"][1])
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1368, in dragScroll
    self.scrollContainer.scroll(ydist)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1396, in scroll
    self.scrollTo(-self.maxOffset + self.height)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1408, in scrollTo
    self.scroll(-self.offset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)


...

Several thousand lines of the above...
...

  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1408, in scrollTo
    self.scroll(-self.offset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1408, in scrollTo
    self.scroll(-self.offset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1408, in scrollTo
    self.scroll(-self.offset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1408, in scrollTo
    self.scroll(-self.offset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1408, in scrollTo
    self.scroll(-self.offset)
  File "/home/linus/Schreibtisch/PyOS 6/pyos.py", line 1400, in scroll
    self.scrollTo(self.minOffset)
RuntimeError: maximum recursion depth exceeded
```

**Comment by furmada** [comment]
Thank you. It was a lot of work, but lots of work unfortunately lets bugs slip in!

This appears to be a problem with how Python OS handles scrolling. More specifically, how it prevents overscroll by moving it down the overscrolled amount. However, I am not immediately sure of what is going on.

I will take a look and try to fix it.

**Comment by furmada** [comment]
I am working on this issue in v1.2.
The scrolling model will likely be rewritten to use the new `computedHeight` measurements for Components.

**Comment by linusg** [comment]
Nice, I'm really looking forward to it! I'm currently working on other things, however, I still would be glad if I could contribute something to this cool project :+1:

**Comment by furmada** [comment]
The bug should be fixed in the latest commit.
